__version__ = "2.0.0"

from elizaos_plugin_polymarket.actions import (
    GammaMarket,
    ResearchActionResult,
    ResearchParams,
    SearchResult,
    cancel_order,
    check_order_scoring,
    create_api_key,
    format_research_action_result,
    format_research_results,
    format_search_results,
    get_account_access_status,
    get_active_orders,
    get_all_api_keys,
    get_balances,
    get_best_price,
    get_clob_markets,
    get_market_details,
    get_markets,
    get_midpoint_price,
    get_open_markets,
    get_open_orders,
    get_order_book,
    get_order_book_depth,
    get_order_details,
    get_positions,
    get_price_history,
    get_sampling_markets,
    get_simplified_markets,
    get_spread,
    get_trade_history,
    handle_authentication,
    handle_realtime_updates,
    place_order,
    # Research market - TS parity
    research_market,
    retrieve_all_markets,
    revoke_api_key,
    # Search markets (Gamma API) - TS parity
    search_markets,
    setup_websocket,
)
from elizaos_plugin_polymarket.constants import (
    CACHE_REFRESH_INTERVAL_SECS,
    CTF_EXCHANGE_ADDRESS,
    DEFAULT_CLOB_API_URL,
    DEFAULT_CLOB_WS_URL,
    DEFAULT_FEE_RATE_BPS,
    DEFAULT_MIN_ORDER_SIZE,
    DEFAULT_PAGE_LIMIT,
    DEFAULT_REQUEST_TIMEOUT_SECS,
    END_CURSOR,
    GAMMA_API_URL,
    LLM_CALL_TIMEOUT_SECS,
    MAX_PAGE_LIMIT,
    MAX_PRICE,
    MIN_PRICE,
    NEG_RISK_ADAPTER_ADDRESS,
    NEG_RISK_CTF_EXCHANGE_ADDRESS,
    POLYGON_CHAIN_ID,
    POLYGON_CHAIN_NAME,
    POLYMARKET_SERVICE_NAME,
    POLYMARKET_WALLET_DATA_CACHE_KEY,
    USDC_ADDRESS,
    USDC_DECIMALS,
    WS_MAX_RECONNECT_ATTEMPTS,
    WS_PING_INTERVAL_SECS,
    WS_RECONNECT_DELAY_SECS,
)
from elizaos_plugin_polymarket.error import PolymarketError, PolymarketErrorCode
from elizaos_plugin_polymarket.providers import (
    ClobClientProvider,
    get_authenticated_clob_client,
    get_clob_client,
    polymarket_provider,
)
from elizaos_plugin_polymarket.service import PolymarketService, PolymarketWalletData
from elizaos_plugin_polymarket.services import (
    MarketResearch,
    ResearchRecommendation,
    ResearchResult,
    ResearchSource,
    ResearchStatus,
    ResearchStorageService,
)
from elizaos_plugin_polymarket.types import (
    ApiKey,
    ApiKeyCreds,
    ApiKeyStatus,
    ApiKeyType,
    Balance,
    BalanceAllowance,
    BookEntry,
    GetTradesParams,
    Market,
    MarketFilters,
    MarketsResponse,
    OpenOrder,
    OrderBook,
    OrderParams,
    OrderResponse,
    OrderSide,
    OrderStatus,
    OrderType,
    Position,
    PriceHistoryEntry,
    Rewards,
    SimplifiedMarket,
    SimplifiedMarketsResponse,
    Token,
    TokenPrice,
    Trade,
    TradeEntry,
    TradesResponse,
    TradeStatus,
)

__all__ = [
    "__version__",
    "ClobClientProvider",
    "get_clob_client",
    "get_authenticated_clob_client",
    "polymarket_provider",
    "PolymarketService",
    "PolymarketWalletData",
    # Market actions
    "get_markets",
    "get_simplified_markets",
    "get_open_markets",
    "get_clob_markets",
    "retrieve_all_markets",
    "get_market_details",
    "get_sampling_markets",
    # Order book actions
    "get_order_book",
    "get_order_book_depth",
    "get_best_price",
    "get_midpoint_price",
    "get_spread",
    # Balance and position actions
    "get_balances",
    "get_positions",
    # Order actions
    "place_order",
    "cancel_order",
    "get_open_orders",
    "get_order_details",
    # Trading actions
    "get_active_orders",
    "get_trade_history",
    "get_price_history",
    "check_order_scoring",
    # API key actions
    "create_api_key",
    "get_all_api_keys",
    "revoke_api_key",
    # Account actions
    "get_account_access_status",
    "handle_authentication",
    # Real-time actions
    "setup_websocket",
    "handle_realtime_updates",
    # Search markets (Gamma API) - TS parity
    "search_markets",
    "SearchResult",
    "GammaMarket",
    "format_search_results",
    # Research market - TS parity
    "research_market",
    "ResearchParams",
    "ResearchActionResult",
    "format_research_results",
    "format_research_action_result",
    # Research storage service - TS parity
    "ResearchStorageService",
    "MarketResearch",
    "ResearchResult",
    "ResearchRecommendation",
    "ResearchSource",
    "ResearchStatus",
    # Types
    "Token",
    "Rewards",
    "Market",
    "SimplifiedMarket",
    "MarketFilters",
    "MarketsResponse",
    "SimplifiedMarketsResponse",
    "OrderSide",
    "OrderType",
    "OrderStatus",
    "OrderParams",
    "OrderResponse",
    "OpenOrder",
    "BookEntry",
    "OrderBook",
    "TradeStatus",
    "Trade",
    "TradeEntry",
    "TradesResponse",
    "GetTradesParams",
    "Position",
    "Balance",
    "BalanceAllowance",
    "ApiKeyCreds",
    "ApiKey",
    "ApiKeyType",
    "ApiKeyStatus",
    "TokenPrice",
    "PriceHistoryEntry",
    "PolymarketError",
    "PolymarketErrorCode",
    # Constants
    "POLYGON_CHAIN_ID",
    "POLYGON_CHAIN_NAME",
    "DEFAULT_CLOB_API_URL",
    "DEFAULT_CLOB_WS_URL",
    "GAMMA_API_URL",
    "POLYMARKET_SERVICE_NAME",
    "POLYMARKET_WALLET_DATA_CACHE_KEY",
    "CACHE_REFRESH_INTERVAL_SECS",
    "DEFAULT_REQUEST_TIMEOUT_SECS",
    "LLM_CALL_TIMEOUT_SECS",
    "DEFAULT_FEE_RATE_BPS",
    "DEFAULT_MIN_ORDER_SIZE",
    "MAX_PRICE",
    "MIN_PRICE",
    "USDC_ADDRESS",
    "USDC_DECIMALS",
    "CTF_EXCHANGE_ADDRESS",
    "NEG_RISK_CTF_EXCHANGE_ADDRESS",
    "NEG_RISK_ADAPTER_ADDRESS",
    "WS_PING_INTERVAL_SECS",
    "WS_RECONNECT_DELAY_SECS",
    "WS_MAX_RECONNECT_ATTEMPTS",
    "DEFAULT_PAGE_LIMIT",
    "MAX_PAGE_LIMIT",
    "END_CURSOR",
]


def get_plugin() -> dict:
    return {
        "name": "@elizaos/plugin-polymarket",
        "description": "Polymarket prediction markets plugin for elizaOS with Python support",
        "version": __version__,
        "actions": [
            get_markets,
            get_simplified_markets,
            get_open_markets,
            get_clob_markets,
            retrieve_all_markets,
            get_market_details,
            get_sampling_markets,
            get_order_book,
            get_order_book_depth,
            get_best_price,
            get_midpoint_price,
            get_spread,
            get_balances,
            get_positions,
            place_order,
            cancel_order,
            get_open_orders,
            get_order_details,
            get_active_orders,
            get_trade_history,
            get_price_history,
            check_order_scoring,
            create_api_key,
            get_all_api_keys,
            revoke_api_key,
            get_account_access_status,
            handle_authentication,
            setup_websocket,
            handle_realtime_updates,
            # Search and research - TS parity
            search_markets,
            research_market,
        ],
        "providers": [
            ClobClientProvider,
        ],
        "services": [
            ResearchStorageService,
        ],
    }
