"""
elizaOS action name constants (TS parity).

The Python implementation in this plugin exposes functional helpers (e.g. `get_markets`)
but does not currently wrap them as elizaOS `Action` objects. These constants provide
the canonical action names used by the TypeScript implementation for cross-language parity.
"""

POLYMARKET_GET_MARKETS = "POLYMARKET_GET_MARKETS"
POLYMARKET_GET_MARKET_DETAILS = "POLYMARKET_GET_MARKET_DETAILS"
POLYMARKET_GET_OPEN_MARKETS = "POLYMARKET_GET_OPEN_MARKETS"
POLYMARKET_GET_CLOB_MARKETS = "POLYMARKET_GET_CLOB_MARKETS"
POLYMARKET_RETRIEVE_ALL_MARKETS = "POLYMARKET_RETRIEVE_ALL_MARKETS"

POLYMARKET_GET_ORDER_BOOK = "POLYMARKET_GET_ORDER_BOOK"
POLYMARKET_GET_ORDER_BOOK_DEPTH = "POLYMARKET_GET_ORDER_BOOK_DEPTH"
POLYMARKET_GET_ORDER_BOOK_SUMMARY = "POLYMARKET_GET_ORDER_BOOK_SUMMARY"
POLYMARKET_GET_BEST_PRICE = "POLYMARKET_GET_BEST_PRICE"
POLYMARKET_GET_MIDPOINT_PRICE = "POLYMARKET_GET_MIDPOINT_PRICE"
POLYMARKET_GET_MIDPOINT = "POLYMARKET_GET_MIDPOINT"
POLYMARKET_GET_SPREAD = "POLYMARKET_GET_SPREAD"

POLYMARKET_GET_BALANCES = "POLYMARKET_GET_BALANCES"
POLYMARKET_GET_POSITIONS = "POLYMARKET_GET_POSITIONS"
POLYMARKET_PLACE_ORDER = "POLYMARKET_PLACE_ORDER"
POLYMARKET_GET_ORDER_DETAILS = "POLYMARKET_GET_ORDER_DETAILS"
POLYMARKET_GET_ACTIVE_ORDERS = "POLYMARKET_GET_ACTIVE_ORDERS"

POLYMARKET_GET_TRADE_HISTORY = "POLYMARKET_GET_TRADE_HISTORY"
POLYMARKET_GET_PRICE_HISTORY = "POLYMARKET_GET_PRICE_HISTORY"
POLYMARKET_CHECK_ORDER_SCORING = "POLYMARKET_CHECK_ORDER_SCORING"

POLYMARKET_CREATE_API_KEY = "POLYMARKET_CREATE_API_KEY"
POLYMARKET_GET_ALL_API_KEYS = "POLYMARKET_GET_ALL_API_KEYS"
POLYMARKET_REVOKE_API_KEY = "POLYMARKET_REVOKE_API_KEY"

POLYMARKET_GET_ACCOUNT_ACCESS_STATUS = "POLYMARKET_GET_ACCOUNT_ACCESS_STATUS"
POLYMARKET_HANDLE_AUTHENTICATION = "POLYMARKET_HANDLE_AUTHENTICATION"

POLYMARKET_SETUP_WEBSOCKET = "POLYMARKET_SETUP_WEBSOCKET"
POLYMARKET_HANDLE_REALTIME_UPDATES = "POLYMARKET_HANDLE_REALTIME_UPDATES"

# Search and Research (TS parity)
POLYMARKET_SEARCH_MARKETS = "POLYMARKET_SEARCH_MARKETS"
POLYMARKET_RESEARCH_MARKET = "POLYMARKET_RESEARCH_MARKET"

ALL_ACTION_NAMES: tuple[str, ...] = (
    POLYMARKET_GET_MARKETS,
    POLYMARKET_GET_MARKET_DETAILS,
    POLYMARKET_GET_OPEN_MARKETS,
    POLYMARKET_GET_CLOB_MARKETS,
    POLYMARKET_RETRIEVE_ALL_MARKETS,
    POLYMARKET_GET_ORDER_BOOK,
    POLYMARKET_GET_ORDER_BOOK_DEPTH,
    POLYMARKET_GET_ORDER_BOOK_SUMMARY,
    POLYMARKET_GET_BEST_PRICE,
    POLYMARKET_GET_MIDPOINT_PRICE,
    POLYMARKET_GET_MIDPOINT,
    POLYMARKET_GET_SPREAD,
    POLYMARKET_GET_BALANCES,
    POLYMARKET_GET_POSITIONS,
    POLYMARKET_PLACE_ORDER,
    POLYMARKET_GET_ORDER_DETAILS,
    POLYMARKET_GET_ACTIVE_ORDERS,
    POLYMARKET_GET_TRADE_HISTORY,
    POLYMARKET_GET_PRICE_HISTORY,
    POLYMARKET_CHECK_ORDER_SCORING,
    POLYMARKET_CREATE_API_KEY,
    POLYMARKET_GET_ALL_API_KEYS,
    POLYMARKET_REVOKE_API_KEY,
    POLYMARKET_GET_ACCOUNT_ACCESS_STATUS,
    POLYMARKET_HANDLE_AUTHENTICATION,
    POLYMARKET_SETUP_WEBSOCKET,
    POLYMARKET_HANDLE_REALTIME_UPDATES,
    POLYMARKET_SEARCH_MARKETS,
    POLYMARKET_RESEARCH_MARKET,
)
