#![allow(missing_docs)]
#![allow(dead_code)]

// elizaOS action name constants (TS parity)

pub const POLYMARKET_GET_MARKETS: &str = "POLYMARKET_GET_MARKETS";
pub const POLYMARKET_GET_MARKET_DETAILS: &str = "POLYMARKET_GET_MARKET_DETAILS";
pub const POLYMARKET_RETRIEVE_ALL_MARKETS: &str = "POLYMARKET_RETRIEVE_ALL_MARKETS";

pub const POLYMARKET_GET_ORDER_BOOK: &str = "POLYMARKET_GET_ORDER_BOOK";
pub const POLYMARKET_GET_ORDER_BOOK_DEPTH: &str = "POLYMARKET_GET_ORDER_BOOK_DEPTH";
pub const POLYMARKET_GET_ORDER_BOOK_SUMMARY: &str = "POLYMARKET_GET_ORDER_BOOK_SUMMARY";
pub const POLYMARKET_GET_BEST_PRICE: &str = "POLYMARKET_GET_BEST_PRICE";
pub const POLYMARKET_GET_MIDPOINT_PRICE: &str = "POLYMARKET_GET_MIDPOINT_PRICE";
pub const POLYMARKET_GET_SPREAD: &str = "POLYMARKET_GET_SPREAD";

pub const POLYMARKET_GET_BALANCES: &str = "POLYMARKET_GET_BALANCES";
pub const POLYMARKET_GET_POSITIONS: &str = "POLYMARKET_GET_POSITIONS";
pub const POLYMARKET_PLACE_ORDER: &str = "POLYMARKET_PLACE_ORDER";
pub const POLYMARKET_GET_ORDER_DETAILS: &str = "POLYMARKET_GET_ORDER_DETAILS";
pub const POLYMARKET_GET_ACTIVE_ORDERS: &str = "POLYMARKET_GET_ACTIVE_ORDERS";

pub const POLYMARKET_GET_TRADE_HISTORY: &str = "POLYMARKET_GET_TRADE_HISTORY";
pub const POLYMARKET_GET_PRICE_HISTORY: &str = "POLYMARKET_GET_PRICE_HISTORY";
pub const POLYMARKET_CHECK_ORDER_SCORING: &str = "POLYMARKET_CHECK_ORDER_SCORING";

pub const POLYMARKET_CREATE_API_KEY: &str = "POLYMARKET_CREATE_API_KEY";
pub const POLYMARKET_GET_ALL_API_KEYS: &str = "POLYMARKET_GET_ALL_API_KEYS";
pub const POLYMARKET_REVOKE_API_KEY: &str = "POLYMARKET_REVOKE_API_KEY";

pub const POLYMARKET_GET_ACCOUNT_ACCESS_STATUS: &str = "POLYMARKET_GET_ACCOUNT_ACCESS_STATUS";
pub const POLYMARKET_HANDLE_AUTHENTICATION: &str = "POLYMARKET_HANDLE_AUTHENTICATION";

pub const POLYMARKET_SETUP_WEBSOCKET: &str = "POLYMARKET_SETUP_WEBSOCKET";
pub const POLYMARKET_HANDLE_REALTIME_UPDATES: &str = "POLYMARKET_HANDLE_REALTIME_UPDATES";

pub const POLYMARKET_SEARCH_MARKETS: &str = "POLYMARKET_SEARCH_MARKETS";
pub const POLYMARKET_RESEARCH_MARKET: &str = "POLYMARKET_RESEARCH_MARKET";

pub const ALL_ACTION_NAMES: &[&str] = &[
    POLYMARKET_GET_MARKETS,
    POLYMARKET_GET_MARKET_DETAILS,
    POLYMARKET_RETRIEVE_ALL_MARKETS,
    POLYMARKET_GET_ORDER_BOOK,
    POLYMARKET_GET_ORDER_BOOK_DEPTH,
    POLYMARKET_GET_ORDER_BOOK_SUMMARY,
    POLYMARKET_GET_BEST_PRICE,
    POLYMARKET_GET_MIDPOINT_PRICE,
    POLYMARKET_GET_SPREAD,
    POLYMARKET_GET_BALANCES,
    POLYMARKET_GET_POSITIONS,
    POLYMARKET_PLACE_ORDER,
    POLYMARKET_GET_ORDER_DETAILS,
    POLYMARKET_GET_ACTIVE_ORDERS,
    POLYMARKET_GET_TRADE_HISTORY,
    POLYMARKET_GET_PRICE_HISTORY,
    POLYMARKET_CHECK_ORDER_SCORING,
    POLYMARKET_CREATE_API_KEY,
    POLYMARKET_GET_ALL_API_KEYS,
    POLYMARKET_REVOKE_API_KEY,
    POLYMARKET_GET_ACCOUNT_ACCESS_STATUS,
    POLYMARKET_HANDLE_AUTHENTICATION,
    POLYMARKET_SETUP_WEBSOCKET,
    POLYMARKET_HANDLE_REALTIME_UPDATES,
    POLYMARKET_SEARCH_MARKETS,
    POLYMARKET_RESEARCH_MARKET,
];
